import { Component, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { templateList, validUsername } from './types';
@Component({standalone:true,imports:[FormsModule,RouterLink],template:`
<main class="landing">
<section class="hero"><div class="eyebrow"><span class="status-dot"></span> YOUR NEXT INTRODUCTION STARTS HERE <span class="version">V 1.0</span></div><h1>Your code tells a story.<br><span>Give it a great introduction.</span></h1><p class="hero-description">Turn your GitHub work into a profile that feels like you.<br>Analyze. Design. Refine with AI. Make your first impression count.</p>
<form class="username-form" (ngSubmit)="start()"><span class="input-prefix">github.com /</span><input [(ngModel)]="username" name="username" aria-label="GitHub username" placeholder="your-username" autocomplete="off" maxlength="39"><button class="button primary" type="submit">Generate my README <span>↗</span></button></form>@if(error){<p class="form-error" role="alert">{{error}}</p>}<div class="hero-meta"><span>✓ Public GitHub data</span><span>✓ Download without sign-in</span><span>✓ Your facts, your voice</span></div></section>
<section class="hero-preview"><div class="preview-window"><div class="window-bar"><div class="window-dots"><i></i><i></i><i></i></div><span>README.md</span><span class="muted">EXAMPLE PREVIEW · NOT AN IMPORTED PROFILE</span></div><div class="example-readme"><div class="example-kicker">HELLO, WORLD.</div><h2>I build things that <span>make a difference.</span></h2><p>A space for my ideas, experiments, and the work I’m proud of.</p><div class="example-badges"><span>PYTHON</span><span>TYPESCRIPT</span><span>FASTAPI</span><span>POSTGRESQL</span></div><div class="example-rule"></div><div class="example-bottom"><div><span class="code-label">01 / ABOUT ME</span><p>Curious by default.<br>Building with intention.</p></div><div><span class="code-label">02 / SELECTED WORK</span><p>Projects with a purpose.<br>Always learning something new.</p></div><div class="example-note"><span>✧</span> YOUR PROFILE.<br>YOUR PERSONALITY.</div></div></div></div><div class="floating-tag">✧ From repository to remarkable</div></section>
<div class="section-heading"><span class="eyebrow">BUILT FOR YOUR WORKFLOW</span><h2>Less formatting.<br>More of what makes you, you.</h2></div><section class="feature-grid"><article><span class="feature-icon">⌘</span><h3>Your work, understood.</h3><p>Analyze real repositories, languages, and documentation. Select the projects that tell your story best.</p><span class="mini-code">github → evidence → introduction</span></article><article><span class="feature-icon purple">✧</span><h3>A second pair of eyes.</h3><p>Generate and refine with AI. Review every proposed change and keep control of your voice.</p><span class="feature-chip">Make it more professional ↗</span></article><article><span class="feature-icon green">◫</span><h3>See it as you write it.</h3><p>Visual controls, a real Markdown editor, and a live preview. Your layout and your code, side by side.</p><div class="tiny-layout"><i></i><i></i><i></i></div></article></section>
<section class="comparison"><div><span class="eyebrow">A LITTLE STRUCTURE GOES A LONG WAY</span><h2>From blank page<br>to a better hello.</h2><p>Start with verified GitHub data, then add your personality.<br>No invented experience. No empty boasts.</p><a class="text-link" routerLink="/studio">Open the studio ↗</a></div><div class="compare-cards"><article class="before"><small>BEFORE</small><pre># Hi 👋\n\nI write code.\n\n...</pre></article><article class="after"><small>AFTER</small><h3>A clear introduction.</h3><p>Your skills. Your projects.<br>A profile worth exploring.</p><span class="example-badges"><span>YOUR STACK</span></span></article></div></section>
<section id="templates"><div class="section-heading row"><div><span class="eyebrow">SIX STARTING POINTS. ENDLESS POSSIBILITIES.</span><h2>Find your kind of README.</h2></div><span class="muted">Designed to be made your own.</span></div><div class="template-gallery">@for(t of templates;track t.id){<button class="template-card" (click)="choose(t.id)"><div class="template-art" [style.--template-accent]="'#'+t.accent"><div class="art-head">{{t.emoji}} / {{t.id.toUpperCase()}}</div><i class="art-title"></i><i></i><div class="art-badges"><b></b><b></b><b></b></div><i></i><i></i></div><div class="template-caption"><h3>{{t.name}}</h3><span>↗</span><p>{{t.subtitle}}</p></div></button>}</div></section>
<section id="how" class="how"><div class="section-heading"><span class="eyebrow">FROM IDEA TO README</span><h2>Three steps. One better profile.</h2></div><div class="steps"><article><span>01</span><h3>Bring your GitHub.</h3><p>Enter your username. We read your public work and help you find the highlights.</p></article><article><span>02</span><h3>Make it yours.</h3><p>Pick a template, refine your words, and preview changes as you make them.</p></article><article><span>03</span><h3>Put it out there.</h3><p>Download your Markdown, or sign in to review a diff and publish to GitHub.</p></article></div></section>
<section class="faq"><div><span class="eyebrow">GOOD QUESTIONS.</span><h2>A few things to know.</h2></div><div>@for(q of faqs;track q.title){<details><summary>{{q.title}} <span>+</span></summary><p>{{q.answer}}</p></details>}</div></section>
<section class="closing"><span class="eyebrow">YOUR GITHUB PROFILE DESERVES MORE THAN A TEMPLATE.</span><h2>Let your work speak.<br>Give it a voice.</h2><a class="button primary" routerLink="/studio">Make my README ↗</a></section><footer><a class="brand" routerLink="/">README<span class="brand-ai">.AI</span></a><span>Designed for developers. Built with care.</span><a routerLink="/studio">Open studio ↗</a></footer></main>`})
export class LandingComponent{
 router=inject(Router);username='';error='';templates=templateList;
 faqs=[{title:'Do I need to sign in?',answer:'No. Analyze public profiles, edit, preview, and download without an account. GitHub sign-in is needed for cloud drafts and publishing.'},{title:'Will AI invent anything about me?',answer:'The AI is instructed to use verified GitHub evidence only. Review all generated claims before publishing; AI can still make mistakes.'},{title:'What if AI is not configured?',answer:'The factual template generator works without an OpenAI key. AI generation and rewriting require a backend OpenAI API key and incur your provider’s usage charges.'},{title:'Will this overwrite my existing README?',answer:'Publishing requires an exact diff preview and explicit confirmation. Changes on GitHub since the preview produce a conflict instead of a silent overwrite.'},{title:'Will the preview look exactly like GitHub?',answer:'The preview approximates GitHub-compatible Markdown. Fonts, themes, sanitization, and third-party widgets may differ from GitHub.'}];
 start(){if(!validUsername(this.username.trim())){this.error='Enter a valid public GitHub username.';return;}this.router.navigate(['/studio'],{queryParams:{username:this.username.trim()}});}
 choose(template:string){this.router.navigate(['/studio'],{queryParams:{template,...(this.username?{username:this.username}:{})}});}
}
